const ActionTypes = {
    // GET_REGION: 'GET_REGION',

    GET_REGIONS: 'GET_REGIONS',
    GET_REGIONS_SUCCEED: 'GET_REGIONS_SUCCEED',
    GET_REGIONS_FAILED: 'GET_REGIONS_FAILED',

    ADD_REGION: 'ADD_REGION',
    ADD_REGION_SUCCEED: 'ADD_REGION_SUCCEED',
    ADD_REGION_FAILED: 'ADD_REGION_FAILED',

    UPDATE_REGION: 'UPDATE_REGION',
    UPDATE_REGION_SUCCEED: 'UPDATE_REGION_SUCCEED',
    UPDATE_REGION_FAILED: 'UPDATE_REGION_FAILED',
    
    DELETE_REGION: 'DELETE_REGION',
    DELETE_REGION_SUCCEED: 'DELETE_REGION_SUCCEED',
    DELETE_REGION_FAILED: 'DELETE_REGION_FAILED',


    GET_USER: 'GET_USER',
    GET_USERS: 'GET_USERS',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER'
}

export default ActionTypes