const ActionTypes = {
    GET_REGION: 'GET_REGION',
    GET_REGIONS: 'GET_REGION',
    ADD_REGION: 'ADD_REGION',
    UPDATE_REGION: 'UPDATE_REGION',
    DELETE_REGION: 'DELETE_REGION',

    GET_USER: 'GET_USER',
    GET_USERS: 'GET_USERS',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER'
}

export default ActionTypes